const LEVELS=[
{
 name:'La fattoria',bg:0,items:[
  {id:'cow',name:'Mucca',emoji:'🐄',audio:'https://upload.wikimedia.org/wikipedia/commons/4/48/Mudchute_cow_1.ogg',tone:[145,125,110]},
  {id:'rooster',name:'Gallo',emoji:'🐓',audio:'https://upload.wikimedia.org/wikipedia/commons/c/c5/Rooster_crowing.ogg',tone:[540,690,820]},
  {id:'sheep',name:'Pecora',emoji:'🐑',audio:'https://upload.wikimedia.org/wikipedia/commons/2/28/Sheep_bleat.ogg',tone:[245,220,205]},
  {id:'horse',name:'Cavallo',emoji:'🐎',audio:'https://upload.wikimedia.org/wikipedia/commons/d/db/Wiehern.ogg',tone:[320,390,275]},
  {id:'pig',name:'Maiale',emoji:'🐖',audio:'https://upload.wikimedia.org/wikipedia/commons/4/4a/Mudchute_pig_2.ogg',tone:[185,230,175]},
  {id:'dog',name:'Cane',emoji:'🐕',audio:'https://upload.wikimedia.org/wikipedia/commons/a/a2/Barking_of_a_dog.ogg',tone:[420,310,430]}
 ]},
{name:'La città',bg:1,items:[{id:'bus',name:'Autobus',emoji:'🚌',tone:[95,105,90]},{id:'siren',name:'Sirena',emoji:'🚨',tone:[520,760,520,760]},{id:'horn',name:'Clacson',emoji:'📣',tone:[330,330,280]},{id:'bell',name:'Campanello',emoji:'🔔',tone:[900,1200,900]},{id:'train',name:'Treno',emoji:'🚆',tone:[120,160,110,150]},{id:'beep',name:'Semaforo',emoji:'🚦',tone:[1100,1100,1100,1100]}]},
{name:'Il mare',bg:2,items:[{id:'wave',name:'Onde',emoji:'🌊',noise:true,tone:[180]},{id:'gull',name:'Gabbiano',emoji:'🐦',tone:[950,1250,850]},{id:'boat',name:'Barca',emoji:'⛵',tone:[105,90,105]},{id:'dolphin',name:'Delfino',emoji:'🐬',tone:[1300,1750,1450]},{id:'splash',name:'Splash',emoji:'💦',noise:true,tone:[420,250]},{id:'shell',name:'Conchiglia',emoji:'🐚',tone:[620,840,1050]}]},
{name:'La montagna',bg:3,items:[{id:'eagle',name:'Aquila',emoji:'🦅',tone:[850,1150,720]},{id:'deer',name:'Cervo',emoji:'🦌',tone:[190,155,210]},{id:'marmot',name:'Marmotta',emoji:'🐿️',tone:[980,1150,980]},{id:'wind',name:'Vento',emoji:'💨',noise:true,tone:[280]},{id:'cowbell',name:'Campanaccio',emoji:'🔔',tone:[540,760,540]},{id:'stream',name:'Ruscello',emoji:'🏞️',noise:true,tone:[680]}]},
{name:'Il bosco',bg:4,items:[{id:'owl',name:'Gufo',emoji:'🦉',tone:[220,180,220]},{id:'woodpecker',name:'Picchio',emoji:'🐦',tone:[720,720,720,720]},{id:'squirrel',name:'Scoiattolo',emoji:'🐿️',tone:[1050,1300,1000]},{id:'frog',name:'Rana',emoji:'🐸',tone:[165,120,165]},{id:'stream',name:'Ruscello',emoji:'💧',noise:true,tone:[640]},{id:'leaves',name:'Foglie',emoji:'🍃',noise:true,tone:[350]}]},
{name:'La giungla',bg:5,items:[{id:'monkey',name:'Scimmia',emoji:'🐒',tone:[520,720,610,820]},{id:'parrot',name:'Pappagallo',emoji:'🦜',tone:[1150,1500,1050]},{id:'jaguar',name:'Giaguaro',emoji:'🐆',tone:[95,120,85]},{id:'toucan',name:'Tucano',emoji:'🐦',tone:[900,1250,1000]},{id:'rain',name:'Pioggia',emoji:'🌧️',noise:true,tone:[500]},{id:'frog',name:'Rana',emoji:'🐸',tone:[150,105,150]}]},
{name:'La notte',bg:6,items:[{id:'owl',name:'Gufo',emoji:'🦉',tone:[220,175,220]},{id:'cricket',name:'Grillo',emoji:'🦗',tone:[1800,1800,1800,1800]},{id:'frog',name:'Rana',emoji:'🐸',tone:[160,110,160]},{id:'wolf',name:'Lupo',emoji:'🐺',tone:[260,310,360,420]},{id:'wind',name:'Vento',emoji:'💨',noise:true,tone:[260]},{id:'nightbird',name:'Uccello',emoji:'🐦',tone:[820,980,780]}]},
{name:'Suoni monelli',bg:7,items:[{id:'fart',name:'Puzzetta',emoji:'💨',tone:[90,70,55],noise:true},{id:'burp',name:'Rutto',emoji:'🥴',tone:[120,90,70]},{id:'raspberry',name:'Pernacchia',emoji:'😛',tone:[170,145,160],noise:true},{id:'sneeze',name:'Starnuto',emoji:'🤧',tone:[650,220],noise:true},{id:'hiccup',name:'Singhiozzo',emoji:'😮',tone:[360,520]},{id:'bla',name:'Bla bla',emoji:'🗯️',tone:[300,420,310,440]}]}
];
const levelIndex=Math.max(0,Math.min(7,Number(new URLSearchParams(location.search).get('level')||0))),level=LEVELS[levelIndex];
document.title='Memory Sonoro · '+level.name;const art=document.querySelector('#art');art.classList.add('l'+level.bg);
let first=null,lock=false,moves=0,pairs=0,enabled=true,ctx,currentAudio=null;const grid=document.querySelector('#grid'),movesEl=document.querySelector('#moves'),pairsEl=document.querySelector('#pairs'),win=document.querySelector('#win');
function shuffle(a){a=[...a];for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
const players=new Map();function audioCtx(){ctx??=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==='suspended')ctx.resume();return ctx}
function noiseBurst(c,t,d=.45,vol=.09){const sr=c.sampleRate,len=Math.floor(sr*d),buf=c.createBuffer(1,len,sr),ch=buf.getChannelData(0);for(let i=0;i<len;i++)ch[i]=(Math.random()*2-1)*(1-i/len);const src=c.createBufferSource(),f=c.createBiquadFilter(),g=c.createGain();src.buffer=buf;f.type='bandpass';f.frequency.value=700;f.Q.value=.65;g.gain.value=vol;src.connect(f).connect(g).connect(c.destination);src.start(t)}
function synth(s){const c=audioCtx(),now=c.currentTime;if(s.noise)noiseBurst(c,now,.5,.075);const seq=s.tone||[220,330,220];seq.forEach((f,i)=>{const o=c.createOscillator(),g=c.createGain(),t=now+i*.13;o.type=(s.id==='siren'||s.id==='monkey')?'sawtooth':(i%2?'triangle':'sine');o.frequency.setValueAtTime(f,t);if(s.id==='wolf')o.frequency.exponentialRampToValueAtTime(f*1.35,t+.24);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(.12,t+.018);g.gain.exponentialRampToValueAtTime(.001,t+.12);o.connect(g).connect(c.destination);o.start(t);o.stop(t+.14)})}
function stopAudio(){if(currentAudio){try{currentAudio.pause();currentAudio.currentTime=0}catch(e){}currentAudio=null}}
function play(s){if(!enabled)return;stopAudio();if(s.audio){let a=players.get(s.id);if(!a){a=new Audio();a.preload='auto';a.src=s.audio;a.volume=1;a.addEventListener('error',()=>{players.delete(s.id);if(currentAudio===a)currentAudio=null;synth(s)},{once:true});players.set(s.id,a)}try{a.pause();a.currentTime=0;currentAudio=a;const p=a.play();if(p&&p.catch)p.catch(()=>{players.delete(s.id);if(currentAudio===a)currentAudio=null;synth(s)});return}catch(e){players.delete(s.id);currentAudio=null}}synth(s)}
function reset(){stopAudio();grid.innerHTML='';first=null;lock=false;moves=pairs=0;movesEl.textContent=0;pairsEl.textContent=0;win.hidden=true;shuffle(level.items.flatMap(x=>[x,x])).forEach(s=>{const b=document.createElement('button');b.className='card';b.innerHTML=`<span class="inner"><span class="face back"></span><span class="face front"><span class="animal">${s.emoji}</span><span class="label">${s.name}</span></span></span>`;b.onclick=()=>pick(b,s);grid.appendChild(b)})}
function pick(card,s){if(lock||card.classList.contains('flipped'))return;card.classList.add('flipped');play(s);if(!first){first={card,s};return}moves++;movesEl.textContent=moves;lock=true;if(first.s.id===s.id){setTimeout(()=>{first.card.classList.add('matched');card.classList.add('matched');pairs++;pairsEl.textContent=pairs;first=null;lock=false;if(pairs===6)setTimeout(()=>win.hidden=false,350)},350)}else{setTimeout(()=>{first.card.classList.remove('flipped');card.classList.remove('flipped');first=null;lock=false},950)}}
document.querySelector('#restart').onclick=reset;document.querySelector('#again').onclick=reset;document.querySelector('#sound').onclick=e=>{enabled=!enabled;if(!enabled)stopAudio();e.currentTarget.textContent=enabled?'🔊':'🔇'};reset();